# Generated by Django 5.2.6 on 2025-09-19 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafikSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasi', models.CharField(max_length=100)),
                ('masa', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('gambar', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
