# Generated by Django 5.2.6 on 2025-09-19 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trafiksnapshot',
            options={'ordering': ['-masa'], 'verbose_name': 'Traffic Snapshot', 'verbose_name_plural': 'Traffic Snapshots'},
        ),
        migrations.AddField(
            model_name='trafiksnapshot',
            name='mode',
            field=models.CharField(choices=[('trafik', 'Traffic View'), ('satelit', 'Satellite View'), ('standard', 'Standard Map')], default='trafik', max_length=20),
        ),
        migrations.AlterField(
            model_name='trafiksnapshot',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trafiksnapshot',
            name='masa',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trafiksnapshot',
            name='status',
            field=models.CharField(choices=[('Lancar', 'Lancar'), ('Sesak', 'Sesak'), ('Kemalangan', 'Kemalangan')], max_length=50),
        ),
    ]
