[build]
# Command to install dependencies
buildCommand = "pip install -r requirements.txt"

# Command to start your bot
start = "python screenshots/screenshot_bot.py "

[deploy]
# Restart the bot automatically if it crashes
restart = true

