name: Scheduled Bot Runner

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r gps_project/requirements.txt


    - name: Run bot
      run: python bot.py

      - name: Show current directory
  run: pwd

- name: List files
  run: ls -la

  - name: Checkout code
  uses: actions/checkout@v3
  with:
    fetch-depth: 0

- name: Checkout code
  uses: actions/checkout@v3
  with:
    fetch-depth: 0

- name: Check for requirements.txt
  run: test -f requirements.txt && echo "✅ Found requirements.txt" || echo "❌ Missing requirements.txt"

- name: Install dependencies
  run: pip install -r requirements.txt
