name: Scheduled Screenshot Bot

on:
  push:
    branches:
      - master
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:

jobs:
  run-screenshot-bot:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set UTF-8 encoding for emoji support
        run: |
          chcp 65001
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV

      - name: Set fallback DATABASE_URL for SQLite
        run: echo "DATABASE_URL=sqlite:///db.sqlite3" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          pip install --use-deprecated=legacy-resolver -r requirements.txt
          pip install selenium

      - name: Run screenshot bot
        run: python gps_project/screenshots/screenshot_bot.py

      - name: Show current directory
        run: pwd

      - name: List files
        run: dir

      - name: Print current UTC time
        run: powershell -Command "Get-Date -Format u"
