name: Screenshot Bot Only

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes
  workflow_dispatch:

jobs:
  run-screenshot-bot:
    runs-on: windows-2022

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Set UTF-8 encoding for emoji support
        run: |
          chcp 65001
          echo "PYTHONIOENCODING=utf-8" >> $GITHUB_ENV

      - name: Set fallback DATABASE_URL for SQLite
        run: echo "DATABASE_URL=sqlite:///db.sqlite3" >> $GITHUB_ENV

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install selenium

      - name: Confirm Django install
        run: python -m django --version

      - name: Set Django settings module
        run: echo "DJANGO_SETTINGS_MODULE=gps_project.settings" >> $GITHUB_ENV

      - name: Run Django migrations
        run: python manage.py migrate

      - name: Collect static files (optional)
        run: python manage.py collectstatic --noinput

      - name: Run screenshot bot
        shell: pwsh
        run: |
          Write-Host "🚦 Running screenshot bot..."
          python gps_project/screenshots/screenshot_bot.py

      - name: List screenshot folder contents
        run: |
          echo "📂 Listing screenshots folder:"
          dir gps_project/screenshots/images

      - name: Show screenshot file info
        run: powershell -Command "Get-ChildItem gps_project/screenshots/images | Select-Object Name, Length, LastWriteTime"

      - name: Print current UTC time
        run: powershell -Command "Get-Date -Format u"